I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 250, in script
    show truc happy
Exception: Image 'truc' does not accept attributes 'happy'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 250, in script
    show truc happy
  File "D:\renpy-8.0.3-sdk\renpy\ast.py", line 1428, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "D:\renpy-8.0.3-sdk\renpy\ast.py", line 1391, in show_imspec
    renpy.config.show(name,
  File "D:\renpy-8.0.3-sdk\renpy\exports.py", line 733, in show
    if not base.find_target() and renpy.config.missing_show:
  File "D:\renpy-8.0.3-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "D:\renpy-8.0.3-sdk\renpy\display\core.py", line 499, in _duplicate
    args.extraneous()
  File "D:\renpy-8.0.3-sdk\renpy\display\core.py", line 362, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'truc' does not accept attributes 'happy'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
Demo 1.0
Sun Oct 22 17:08:17 2023
